"""add_fee_fields_to_upload

Revision ID: bc13705c9612
Revises: 4a520c9c4143
Create Date: 2026-04-28 19:01:56.457748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc13705c9612'
down_revision: Union[str, Sequence[str], None] = '4a520c9c4143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('settlement_fee', sa.Numeric(), nullable=False, server_default='0'))
    op.add_column('upload', sa.Column('registration_fee', sa.Numeric(), nullable=False, server_default='0'))
    op.add_column('upload', sa.Column('term_fee', sa.Numeric(), nullable=False, server_default='0'))
    op.add_column('upload', sa.Column('ana_fee', sa.Numeric(), nullable=False, server_default='0'))
    op.add_column('upload', sa.Column('emoluments', sa.Numeric(), nullable=False, server_default='0'))
    op.add_column('upload', sa.Column('operational_fee', sa.Numeric(), nullable=False, server_default='0'))
    op.add_column('upload', sa.Column('execution', sa.Numeric(), nullable=False, server_default='0'))
    op.add_column('upload', sa.Column('custody_fee', sa.Numeric(), nullable=False, server_default='0'))
    op.add_column('upload', sa.Column('taxes', sa.Numeric(), nullable=False, server_default='0'))
    op.add_column('upload', sa.Column('irrf', sa.Numeric(), nullable=False, server_default='0'))
    op.add_column('upload', sa.Column('other_fees', sa.Numeric(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'other_fees')
    op.drop_column('upload', 'irrf')
    op.drop_column('upload', 'taxes')
    op.drop_column('upload', 'custody_fee')
    op.drop_column('upload', 'execution')
    op.drop_column('upload', 'operational_fee')
    op.drop_column('upload', 'emoluments')
    op.drop_column('upload', 'ana_fee')
    op.drop_column('upload', 'term_fee')
    op.drop_column('upload', 'registration_fee')
    op.drop_column('upload', 'settlement_fee')
    # ### end Alembic commands ###
